services:
  - type: web
    name: videochat-signaling
    env: node
    rootDir: signaling
    buildCommand: npm ci --include=dev && npm run build
    startCommand: node dist/index.js
    healthCheckPath: /healthz
    autoDeploy: true
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: "https://nirmallya-koner.vercel.app"